#!/usr/bin/env python3
"""
============================================================================
EDIT TOOL — DECORATOR PATTERN
============================================================================

PATTERN: @tool Decorator
────────────────────────────────────────────────────────────────────────────
Wraps Matimo tool calls in a class using the @tool("tool-name") decorator.
The decorator intercepts method calls and routes them through Matimo
automatically — the method body is never executed.

Use this pattern when:
  ✅ Building class-based applications or services
  ✅ Encapsulating file editing logic in strongly-typed wrappers
  ✅ Combining multiple tools in a single service layer
  ✅ Object-oriented design

SETUP:
────────────────────────────────────────────────────────────────────────────
  No API key required — edit is a built-in core tool.

USAGE:
────────────────────────────────────────────────────────────────────────────
  export MATIMO_AUTO_APPROVE=true
  uv run python edit/edit_decorator.py

⚠️  WARNING: This tool modifies files on disk. Use with caution!

============================================================================
"""

import asyncio
import os
import tempfile
from pathlib import Path
from dotenv import load_dotenv

from matimo import Matimo
from matimo.decorators import set_global_matimo_instance, tool

load_dotenv(Path(__file__).parent.parent.parent / ".env")


# ───────────────────────────────────────────────────────────────────────────
# Service class — each method is auto-routed to the matching Matimo tool
# ───────────────────────────────────────────────────────────────────────────

class FileEditor:
    """High-level file editing service using the @tool decorator pattern."""

    @tool("edit")
    async def write_file(self, file_path: str, new_content: str) -> dict:
        """
        Decorator auto-calls matimo.execute('edit', {...}).
        
        Args:
            file_path: Path to file to edit
            new_content: New content to write
            
        Returns:
            Edit result
        """
        ...

    @tool("edit")
    async def create_file(
        self,
        file_path: str,
        new_content: str,
        create_if_missing: bool = True
    ) -> dict:
        """Create a new file with content."""
        ...

    @tool("edit")
    async def update_python_file(self, file_path: str, new_content: str) -> dict:
        """Update a Python file."""
        ...


# ───────────────────────────────────────────────────────────────────────────
# Main
# ───────────────────────────────────────────────────────────────────────────

async def main() -> None:
    print("\n╔════════════════════════════════════════════════════════╗")
    print("║     Edit Tool — Decorator Pattern                    ║")
    print("║     (@tool decorators for automatic execution)       ║")
    print("║     ⚠️  WARNING: This modifies files!                ║")
    print("╚════════════════════════════════════════════════════════╝\n")

    # ── Initialize Matimo and register globally for the decorator ────────────
    print("🚀  Initializing Matimo…")
    matimo = await Matimo.init(auto_discover=True)
    set_global_matimo_instance(matimo)
    print("✅  Matimo initialized\n")

    editor = FileEditor()

    try:
        # Create a temporary file for testing
        with tempfile.NamedTemporaryFile(mode='w', delete=False, suffix='.txt') as tmp:
            tmp_path = tmp.name
            tmp.write("Original content\n")

        print("Created temporary file for testing…\n")

        # Example 1: Write to existing file
        print("1. Writing new content to temporary file\n")
        new_content = "Updated content from decorator\nLine 2\nLine 3\n"
        result1 = await editor.write_file(tmp_path, new_content)
        
        if result1.get("success"):
            print("File written successfully")
            with open(tmp_path, 'r') as f:
                content = f.read()
            print(f"Verified content:\n{content}")
        else:
            print(f"Failed: {result1.get('error')}")
        print("---\n")

        # Example 2: Create a new Python file
        print("2. Creating a new Python file\n")
        _fd, new_py_file = tempfile.mkstemp(suffix='.py', prefix='test_')
        os.close(_fd)
        python_content = '''#!/usr/bin/env python3
"""Auto-generated by Matimo decorator example."""

def main():
    print("Hello from decorator-generated file!")

if __name__ == "__main__":
    main()
'''
        
        result2 = await editor.create_file(new_py_file, python_content)
        if result2.get("success"):
            print(f"Python file created: {Path(new_py_file).name}")
            if Path(new_py_file).exists():
                print("✓ File verified on disk")
        else:
            print(f"Failed: {result2.get('error')}")
        print("---\n")

        # Example 3: Update Python file
        print("3. Updating Python file\n")
        updated_python = '''#!/usr/bin/env python3
"""Updated by decorator pattern."""

import sys

def main():
    print("Updated content")
    print(f"Python version: {sys.version}")

if __name__ == "__main__":
    main()
'''
        
        result3 = await editor.update_python_file(new_py_file, updated_python)
        if result3.get("success"):
            print("Python file updated successfully")
            with open(new_py_file, 'r') as f:
                lines = f.readlines()
            print(f"File now has {len(lines)} lines")
        else:
            print(f"Failed: {result3.get('error')}")
        print("---\n")

        # Clean up
        print("Cleaning up temporary files…")
        Path(tmp_path).unlink(missing_ok=True)
        if Path(new_py_file).exists():
            Path(new_py_file).unlink()
        print("✓ Cleanup complete\n")

    except Exception as error:
        print(f"❌  Error: {error}\n")


if __name__ == "__main__":
    asyncio.run(main())
