packages:
  - "packages/bruno"
  - "packages/core"
  - "packages/slack"
  - "packages/gmail"
  - "packages/github"
  - "packages/hubspot"
  - "packages/notion"
  - "packages/mailchimp"
  - "packages/twilio"
  - "packages/cli"
  - "examples/tools"
  - "examples/mcp"
  - "packages/postgres"
